<?xml version="1.0" encoding="utf-8"?><Database Name="bug_tracker" Class="BugTrackerDbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=bug_tracker;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bug_trackerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bug_tracker_menu_headers" Member="bug_tracker_menu_headers">
    <Type Name="bug_tracker_menu_header">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="menu_title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="has_submenu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="top_level" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="bug_tracker_menu_header_bug_tracker_menu_page" Member="bug_tracker_menu_pages" ThisKey="id" OtherKey="menu_id" Type="bug_tracker_menu_page" />
      <Association Name="bug_tracker_menu_header_bug_tracker_menu_submenus" Member="bug_tracker_menu_submenus" ThisKey="id" OtherKey="menu_header_id" Type="bug_tracker_menu_submenus" />
      <Association Name="bug_tracker_menu_header_bug_tracker_menu_submenus1" Member="bug_tracker_menu_submenus1" ThisKey="id" OtherKey="submenu_id" Type="bug_tracker_menu_submenus" />
    </Type>
  </Table>
  <Table Name="dbo.bug_tracker_pages" Member="bug_tracker_pages">
    <Type Name="bug_tracker_page">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="page_url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="friendly_url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sequence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="bug_tracker_page_bug_tracker_menu_page" Member="bug_tracker_menu_pages" ThisKey="id" OtherKey="page_id" Type="bug_tracker_menu_page" />
    </Type>
  </Table>
  <Table Name="dbo.bug_tracker_menu_pages" Member="bug_tracker_menu_pages">
    <Type Name="bug_tracker_menu_page">
      <Column Name="menu_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="page_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="bug_tracker_menu_header_bug_tracker_menu_page" Member="bug_tracker_menu_header" ThisKey="menu_id" OtherKey="id" Type="bug_tracker_menu_header" IsForeignKey="true" />
      <Association Name="bug_tracker_page_bug_tracker_menu_page" Member="bug_tracker_page" ThisKey="page_id" OtherKey="id" Type="bug_tracker_page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.bug_tracker_menu_submenus" Member="bug_tracker_menu_submenus">
    <Type Name="bug_tracker_menu_submenus">
      <Column Name="menu_header_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="submenu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="bug_tracker_menu_header_bug_tracker_menu_submenus" Member="bug_tracker_menu_header" ThisKey="menu_header_id" OtherKey="id" Type="bug_tracker_menu_header" IsForeignKey="true" />
      <Association Name="bug_tracker_menu_header_bug_tracker_menu_submenus1" Member="bug_tracker_menu_header1" ThisKey="submenu_id" OtherKey="id" Type="bug_tracker_menu_header" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ticket_priority" Member="ticket_priorities">
    <Type Name="ticket_priority">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Association Name="ticket_priority_ticket" Member="tickets" ThisKey="id" OtherKey="priority" Type="ticket" />
    </Type>
  </Table>
  <Table Name="dbo.ticket_status" Member="ticket_status">
    <Type Name="ticket_status">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ticket_status_ticket" Member="tickets" ThisKey="id" OtherKey="status" Type="ticket" />
    </Type>
  </Table>
  <Table Name="dbo.log_type" Member="log_types">
    <Type Name="log_type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="log_type" Member="log_type1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="log_type_log" Member="logs" ThisKey="id" OtherKey="log_type" Type="log" />
    </Type>
  </Table>
  <Table Name="dbo.logs" Member="logs">
    <Type Name="log">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="obj_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="log_description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="exception_messaage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="exception_stacktrace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="log_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userid" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="log_type_log" Member="log_type1" ThisKey="log_type" OtherKey="id" Type="log_type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.notes" Member="notes">
    <Type Name="note">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ticket_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="creator_id" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="ticket_note" Member="ticket" ThisKey="ticket_id" OtherKey="id" Type="ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ticket_attachment" Member="ticket_attachments">
    <Type Name="ticket_attachment">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ticket_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="attachment_location" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ticket_ticket_attachment" Member="ticket" ThisKey="ticket_id" OtherKey="id" Type="ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.bug_tracker_menu_roles" Member="bug_tracker_menu_roles">
    <Type Name="bug_tracker_menu_role">
      <Column Name="menu_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bug_tracker_pages_roles" Member="bug_tracker_pages_roles">
    <Type Name="bug_tracker_pages_role">
      <Column Name="page_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bug_tracker_roles_id" Member="bug_tracker_roles_ids">
    <Type Name="bug_tracker_roles_id">
      <Column Name="role_id" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="page_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.projects_users" Member="projects_users">
    <Type Name="projects_user">
      <Column Name="project_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="user_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="project_projects_user" Member="project" ThisKey="project_id" OtherKey="id" Type="project" IsForeignKey="true" />
      <Association Name="aspnet_User_projects_user" Member="aspnet_User" ThisKey="user_id" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.projects" Member="projects">
    <Type Name="project">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="created_by" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="project_projects_user" Member="projects_users" ThisKey="id" OtherKey="project_id" Type="projects_user" />
      <Association Name="project_ticket" Member="tickets" ThisKey="id" OtherKey="project_id" Type="ticket" />
      <Association Name="aspnet_User_project" Member="aspnet_User" ThisKey="created_by" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_projects_user" Member="projects_users" ThisKey="UserId" OtherKey="user_id" Type="projects_user" />
      <Association Name="aspnet_User_project" Member="projects" ThisKey="UserId" OtherKey="created_by" Type="project" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tickets" Member="tickets">
    <Type Name="ticket">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_by" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dev_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="project_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="ticket_note" Member="notes" ThisKey="id" OtherKey="ticket_id" Type="note" />
      <Association Name="ticket_ticket_attachment" Member="ticket_attachments" ThisKey="id" OtherKey="ticket_id" Type="ticket_attachment" />
      <Association Name="ticket_priority_ticket" Member="ticket_priority" ThisKey="priority" OtherKey="id" Type="ticket_priority" IsForeignKey="true" />
      <Association Name="project_ticket" Member="project" ThisKey="project_id" OtherKey="id" Type="project" IsForeignKey="true" />
      <Association Name="ticket_status_ticket" Member="ticket_status" ThisKey="status" OtherKey="id" Type="ticket_status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.projects_tickets_details" Member="projects_tickets_details">
    <Type Name="projects_tickets_detail">
      <Column Name="project_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Total Tickets]" Member="Total_Tickets" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Open Tickets]" Member="Open_Tickets" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Managers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Devs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Users" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.project_details" Member="project_details">
    <Type Name="project_detail">
      <Column Name="ticket_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="created_by" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="dev" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="project_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>